name: develop

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: slacgismo/gridlabd:develop

    steps:
    - uses: actions/checkout@v2
    - uses: nelonoel/branch-name@v1
    - name: Get test files
      run: |
        git submodule sync
        git submodule update --init --recursive
    - name: Validation
      run: |
        echo 'GITUSER="slacgismo"' > $(gridlabd --version=install)/share/gridlabd/gridlabd-template.conf
        echo 'GITBRANCH="'${BRANCH_NAME}'"' >> $(gridlabd --version=install)/share/gridlabd/gridlabd-template.conf
        make validate
    - name: Save results
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: validate-result
        path: |
          validate.txt
          validate.tar.gz