name: develop

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: lfenergy/arras:develop

    steps:
    - uses: actions/checkout@v3
    
    - name: Get test files
      run: |
        git config --global --add safe.directory /__w/gridlabd-template/gridlabd-template
        git submodule sync
        git submodule update --init --recursive
        
    - name: Validation
      run: |
        make validate VERBOSE=yes DEBUG=yes
        
    - name: Save results
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: validate-result
        path: |
          validate.txt
          validate.tar.gz
