name: master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: slacgismo/gridlabd:latest

    steps:
    - uses: actions/checkout@v2
    - name: Get test files
      run: |
        git submodule sync
        git submodule update --init --recursive
    - name: Validation
      run: |
        make validate
    - name: Save results
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: validate-result
        path: |
          validate.txt
          validate.tar.gz